name: uvfl_wallet
description: UVFL Value Wallet MVP
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  drift: ^2.20.0
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0

  uuid: ^4.5.1

  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3

  dio: ^5.7.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.20.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
